trigger:
  branches:
    include:
    - main
pool: bipinpool

stages:
- stage: TerraformInitPlan
  displayName: Terraform Init Plan
  jobs:
  - job: TerraformInitPlan
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '/env/*'
    
